<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="my_robot">

  <!-- xacro properties -->
  <xacro:property name="platform_length" value="0.5"/>
  <xacro:property name="platform_width" value="0.5"/>
  <xacro:property name="platform_thickness" value="0.01"/>
  <xacro:property name="body_length" value="0.5"/>
  <xacro:property name="body_width" value="0.3"/>
  <xacro:property name="body_height" value="0.1"/>

  <xacro:property name="track_length" value="0.5"/>
  <xacro:property name="track_width" value="0.1"/>
  <xacro:property name="track_height" value="0.1"/>

  <!-- LiDAR properties: diameter 5cm (radius 2.5cm), height 3cm -->
  <xacro:property name="lidar_radius" value="0.025"/>
  <xacro:property name="lidar_height" value="0.03"/>

  <!-- World link: the root of the robot model, used to avoid KDL parser warning -->
  <link name="world"/>

  <!-- Connect world link to base_link -->
  <joint name="world_to_base_link" type="fixed">
    <parent link="world"/>
    <child link="base_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <link name="base_link">
    <!-- Base link needs an inertial block for Gazebo simulation -->
    <visual>
      <geometry>
        <box size="0.001 0.001 0.001"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <material name="Green">
        <color rgba="0 1 0 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="0.001 0.001 0.001"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </collision>
    <inertial>
      <mass value="0.001"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.000001" ixy="0.0" ixz="0.0"
               iyy="0.000001" iyz="0.0"
               izz="0.000001"/>
    </inertial>
  </link>

  <link name="bottom_plate">
    <visual>
      <geometry>
        <box size="${platform_length} ${platform_width} ${platform_thickness}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <material name="yellow">
        <color rgba="1.0 1.0 0.0 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${platform_length} ${platform_width} ${platform_thickness}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </collision>
    <inertial>
      <mass value="0.5"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0"
               iyy="0.01" iyz="0.0"
               izz="0.01"/>
    </inertial>
  </link>

  <joint name="base_to_bottom" type="fixed">
    <parent link="base_link"/>
    <child link="bottom_plate"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <link name="main_body">
    <visual>
      <geometry>
        <box size="${body_length} ${body_width} ${body_height}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <material name="yellow"/>
    </visual>
    <collision>
      <geometry>
        <box size="${body_length} ${body_width} ${body_height}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </collision>
    <inertial>
      <mass value="1.0"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.05" ixy="0.0" ixz="0.0"
               iyy="0.05" iyz="0.0"
               izz="0.05"/>
    </inertial>
  </link>

  <joint name="bottom_to_body" type="fixed">
    <parent link="bottom_plate"/>
    <child link="main_body"/>
    <origin xyz="0 0 ${platform_thickness/2 + body_height/2}" rpy="0 0 0"/>
  </joint>

  <link name="top_plate">
    <visual>
      <geometry>
        <box size="${platform_length} ${platform_width} ${platform_thickness}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <material name="yellow"/>
    </visual>
    <collision>
      <geometry>
        <box size="${platform_length} ${platform_width} ${platform_thickness}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </collision>
    <inertial>
      <mass value="0.5"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.01" ixy="0.0" ixz="0.0"
               iyy="0.01" iyz="0.0"
               izz="0.01"/>
    </inertial>
  </link>

  <joint name="body_to_top" type="fixed">
    <parent link="main_body"/>
    <child link="top_plate"/>
    <origin xyz="0 0 ${body_height/2 + platform_thickness/2}" rpy="0 0 0"/>
  </joint>

  <link name="left_track">
    <visual>
      <geometry>
        <box size="${track_length} ${track_width} ${track_height}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <material name="black">
        <color rgba="0.1 0.1 0.1 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${track_length} ${track_width} ${track_height}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </collision>
    <inertial>
      <mass value="0.2"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.005" ixy="0.0" ixz="0.0"
               iyy="0.005" iyz="0.0"
               izz="0.005"/>
    </inertial>
  </link>

  <joint name="base_to_left_track" type="fixed">
    <parent link="base_link"/>
    <child link="left_track"/>
    <origin xyz="0 ${platform_width/2 + 0.01 - track_width/2} ${-platform_thickness/2 - track_height/2}" rpy="0 0 0"/>
  </joint>

  <link name="right_track">
    <visual>
      <geometry>
        <box size="${track_length} ${track_width} ${track_height}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <material name="black"/>
    </visual>
    <collision>
      <geometry>
        <box size="${track_length} ${track_width} ${track_height}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </collision>
    <inertial>
      <mass value="0.2"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.005" ixy="0.0" ixz="0.0"
               iyy="0.005" iyz="0.0"
               izz="0.005"/>
    </inertial>
  </link>

  <joint name="base_to_right_track" type="fixed">
    <parent link="base_link"/>
    <child link="right_track"/>
    <origin xyz="0 ${-(platform_width/2 + 0.01 - track_width/2)} ${-platform_thickness/2 - track_height/2}" rpy="0 0 0"/>
  </joint>

  <!-- LiDAR Sensor Link -->
  <link name="lidar_link">
    <visual>
      <geometry>
        <cylinder radius="${lidar_radius}" length="${lidar_height}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <material name="Red">
        <color rgba="1 0 0 1"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${lidar_radius}" length="${lidar_height}"/>
      </geometry>
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </collision>
    <inertial>
      <mass value="0.05"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
               iyy="0.0001" iyz="0.0"
               izz="0.0001"/>
    </inertial>
  </link>

  <!-- Joint to attach LiDAR to top_plate -->
  <joint name="lidar_joint" type="fixed">
    <parent link="top_plate"/>
    <child link="lidar_link"/>
    <!-- Position LiDAR on top of the top_plate -->
    <origin xyz="0 0 ${platform_thickness/2 + lidar_height/2}" rpy="0 0 0"/>
  </joint>

  <!-- Gazebo-specific extensions (sensors and plugins) -->
  <gazebo reference="lidar_link">
    <sensor name="lidar" type="gpu_lidar">
      <pose>0 0 0 0 0 0</pose>
      <topic>/scan</topic>
      <update_rate>10</update_rate>
      <ray>
        <scan>
          <horizontal>
            <samples>640</samples>
            <resolution>1</resolution>
            <min_angle>-3.14</min_angle>
            <max_angle>3.14</max_angle>
          </horizontal>
          <vertical>
            <samples>1</samples>
            <resolution>0.01</resolution>
            <min_angle>0</min_angle>
            <max_angle>0</max_angle>
          </vertical>
        </scan>
        <range>
          <min>0.1</min>
          <max>10.0</max>
          <resolution>0.01</resolution>
        </range>
      </ray>
      <always_on>1</always_on>
      <visualize>true</visualize>
    </sensor>
  </gazebo>
  
  <gazebo>
    <plugin filename="gz-sim-sensors-system" name="gz::sim::systems::Sensors">
      <render_engine>ogre2</render_engine>
    </plugin>
  </gazebo>

</robot>
