<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="my_robot">

  <!-- ======================= คุณสมบัติต่างๆ (Properties) ======================= -->
  <xacro:property name="body_length" value="0.35"/>
  <xacro:property name="body_width" value="0.3"/>
  <xacro:property name="body_height" value="0.2"/>
  <xacro:property name="track_length" value="0.5"/>
  <xacro:property name="track_width" value="0.1"/>
  <xacro:property name="track_height" value="0.18"/>
  <xacro:property name="lidar_radius" value="0.025"/>
  <xacro:property name="lidar_height" value="0.03"/>
  <xacro:property name="wheel_radius" value="0.021"/>
  <xacro:property name="wheel_thickness" value="0.001"/>
  <xacro:property name="wheel_z_offset" value="-0.07"/>
  <xacro:property name="top_plate_length" value="0.5"/>
  <xacro:property name="top_plate_width" value="0.5"/>
  <xacro:property name="top_plate_thickness" value="0.003"/>
  <xacro:property name="lidar_stand_length" value="0.5"/>
  <xacro:property name="lidar_stand_width" value="0.3"/>
  <xacro:property name="lidar_stand_height" value="0.1"/>
  <!-- ## NEW: คุณสมบัติสำหรับ Plate วาง Lidar ## -->
  <xacro:property name="lidar_plate_length" value="0.5"/>
  <xacro:property name="lidar_plate_width" value="0.5"/>
  <xacro:property name="lidar_plate_thickness" value="0.003"/>


  <!-- ======================= สีของวัสดุ (Materials) ======================= -->
  <material name="black"><color rgba="0.1 0.1 0.1 1.0"/></material>
  <material name="yellow"><color rgba="1.0 1.0 0.0 1.0"/></material>
  <material name="red"><color rgba="1 0 0 1"/></material>
  <material name="white"><color rgba="1.0 1.0 1.0 1.0"/></material>

  <!-- ======================= โครงสร้างหุ่นยนต์ (Robot Structure) ======================= -->
  <link name="base_footprint"/>

  <link name="base_link">
    <visual>
      <geometry><box size="${body_length} ${body_width} ${body_height}"/></geometry>
      <material name="yellow"/>
    </visual>
    <collision>
      <geometry><box size="${body_length*0.9} ${body_width*0.9} ${body_height*0.9}"/></geometry>
    </collision>
    <inertial>
      <mass value="5.0"/>
      <inertia ixx="0.4" ixy="0" ixz="0" iyy="0.4" iyz="0" izz="0.2"/>
    </inertial>
  </link>
  <joint name="base_footprint_joint" type="fixed">
    <parent link="base_footprint"/>
    <child link="base_link"/>
    <origin xyz="0 0 ${wheel_radius - wheel_z_offset}"/>
  </joint>

  <xacro:macro name="track_housing" params="prefix side">
    <link name="${prefix}_track">
      <visual>
        <geometry><box size="${track_length} ${track_width} ${track_height}"/></geometry>
        <material name="black"/>
      </visual>
    </link>
    <joint name="base_to_${prefix}_track" type="fixed">
      <parent link="base_link"/>
      <child link="${prefix}_track"/>
      <origin xyz="0 ${side * (body_width/2 + track_width/2)} ${-body_height/2 + track_height/2}"/>
    </joint>
  </xacro:macro>
  <xacro:track_housing prefix="left" side="1"/>
  <xacro:track_housing prefix="right" side="-1"/>

  <xacro:macro name="drive_wheel" params="prefix side">
    <link name="${prefix}_wheel">
      <visual>
        <origin rpy="${pi/2} 0 0"/>
        <geometry><cylinder radius="${wheel_radius}" length="${wheel_thickness}"/></geometry>
        <material name="white"/>
      </visual>
      <collision>
        <origin rpy="${pi/2} 0 0"/>
        <geometry><cylinder radius="${wheel_radius}" length="${wheel_thickness}"/></geometry>
      </collision>
      <inertial>
        <mass value="0.5"/>
        <inertia ixx="0.001" ixy="0" ixz="0" iyy="0.001" iyz="0" izz="0.001"/>
      </inertial>
    </link>
    <joint name="${prefix}_wheel_joint" type="continuous">
      <parent link="base_link"/>
      <child link="${prefix}_wheel"/>
      <origin xyz="0 ${side * (body_width/2 + track_width + wheel_thickness/2)} ${wheel_z_offset}"/>
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro>
  <xacro:drive_wheel prefix="left"  side="1"/>
  <xacro:drive_wheel prefix="right" side="-1"/>

  <link name="top_plate">
    <visual>
      <geometry><box size="${top_plate_length} ${top_plate_width} ${top_plate_thickness}"/></geometry>
      <material name="yellow"/>
    </visual>
    <collision>
      <geometry><box size="${top_plate_length} ${top_plate_width} ${top_plate_thickness}"/></geometry>
    </collision>
    <inertial>
      <mass value="0.5"/>
      <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
    </inertial>
  </link>
  <joint name="top_plate_joint" type="fixed">
    <parent link="base_link"/>
    <child link="top_plate"/>
    <origin xyz="0 0 ${body_height/2 + top_plate_thickness/2}"/>
  </joint>

  <link name="lidar_stand">
    <visual>
      <geometry><box size="${lidar_stand_length} ${lidar_stand_width} ${lidar_stand_height}"/></geometry>
      <material name="yellow"/>
    </visual>
    <collision>
      <geometry><box size="${lidar_stand_length} ${lidar_stand_width} ${lidar_stand_height}"/></geometry>
    </collision>
    <inertial>
      <mass value="0.2"/>
      <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
    </inertial>
  </link>
  <joint name="lidar_stand_joint" type="fixed">
    <parent link="top_plate"/>
    <child link="lidar_stand"/>
    <origin xyz="0 0 ${top_plate_thickness/2 + lidar_stand_height/2}"/>
  </joint>

  <!-- ## NEW: สร้าง Plate สำหรับวาง Lidar ## -->
  <link name="lidar_plate">
    <visual>
      <geometry><box size="${lidar_plate_length} ${lidar_plate_width} ${lidar_plate_thickness}"/></geometry>
      <material name="yellow"/>
    </visual>
    <collision>
      <geometry><box size="${lidar_plate_length} ${lidar_plate_width} ${lidar_plate_thickness}"/></geometry>
    </collision>
    <inertial>
      <mass value="0.1"/>
      <inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6"/>
    </inertial>
  </link>
  <joint name="lidar_plate_joint" type="fixed">
    <parent link="lidar_stand"/>
    <child link="lidar_plate"/>
    <origin xyz="0 0 ${lidar_stand_height/2 + lidar_plate_thickness/2}"/>
  </joint>

  <link name="lidar_link">
    <visual>
      <geometry><cylinder radius="${lidar_radius}" length="${lidar_height}"/></geometry>
      <material name="red"/>
    </visual>
    <collision>
      <geometry><cylinder radius="${lidar_radius}" length="${lidar_height}"/></geometry>
    </collision>
    <inertial><mass value="0.1"/><inertia ixx="1e-6" ixy="0" ixz="0" iyy="1e-6" iyz="0" izz="1e-6"/></inertial>
  </link>
  <joint name="lidar_joint" type="fixed">
    <!-- ## FIX: ย้าย Lidar ไปยึดกับ Plate ที่สร้างขึ้นใหม่ ## -->
    <parent link="lidar_plate"/>
    <child link="lidar_link"/>
    <origin xyz="0 0 ${lidar_plate_thickness/2 + lidar_height/2}"/>
  </joint>

  <xacro:include filename="my_robot.gazebo.xacro" />
</robot>
