<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro" name="my_robot">

  <!-- Body Dimensions: 50cm x 50cm x 30cm -->
  <xacro:property name="body_length" value="0.5"/>  <!-- Y-axis -->
  <xacro:property name="body_width"  value="0.5"/>  <!-- X-axis -->
  <xacro:property name="body_height" value="0.3"/>  <!-- Z-axis -->

  <!-- Tracks -->
  <xacro:property name="track_length" value="${body_length}"/>
  <xacro:property name="track_width" value="0.05"/>
  <xacro:property name="track_height" value="0.1"/>

  <link name="world"/>

  <joint name="world_to_base" type="fixed">
    <parent link="world"/>
    <child link="base_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <link name="base_link">
    <visual>
      <geometry>
        <box size="${body_length} ${body_width} ${body_height}"/>
      </geometry>
      <material name="yellow">
        <color rgba="1.0 1.0 0.0 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${body_length} ${body_width} ${body_height}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="5.0"/>
      <inertia ixx="0.05" iyy="0.05" izz="0.05" ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <link name="left_track">
    <visual>
      <geometry>
        <box size="${track_length} ${track_width} ${track_height}"/>
      </geometry>
      <origin xyz="0 ${body_width/2 + track_width/2} ${-body_height/2 + track_height/2}" rpy="0 0 0"/>
      <material name="dark_gray">
        <color rgba="0.2 0.2 0.2 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${track_length} ${track_width} ${track_height}"/>
      </geometry>
      <origin xyz="0 ${body_width/2 + track_width/2} ${-body_height/2 + track_height/2}" rpy="0 0 0"/>
    </collision>
    <inertial>
      <mass value="1.0"/>
      <inertia ixx="0.01" iyy="0.01" izz="0.01" ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <link name="right_track">
    <visual>
      <geometry>
        <box size="${track_length} ${track_width} ${track_height}"/>
      </geometry>
      <origin xyz="0 ${-(body_width/2 + track_width/2)} ${-body_height/2 + track_height/2}" rpy="0 0 0"/>
      <material name="dark_gray">
        <color rgba="0.2 0.2 0.2 1.0"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <box size="${track_length} ${track_width} ${track_height}"/>
      </geometry>
      <origin xyz="0 ${-(body_width/2 + track_width/2)} ${-body_height/2 + track_height/2}" rpy="0 0 0"/>
    </collision>
    <inertial>
      <mass value="1.0"/>
      <inertia ixx="0.01" iyy="0.01" izz="0.01" ixy="0" ixz="0" iyz="0"/>
    </inertial>
  </link>

  <joint name="base_to_left_track" type="fixed">
    <parent link="base_link"/>
    <child link="left_track"/>
    <origin xyz="0 ${body_width/2 + track_width/2} ${-body_height/2 + track_height/2}" rpy="0 0 0"/>
  </joint>

  <joint name="base_to_right_track" type="fixed">
    <parent link="base_link"/>
    <child link="right_track"/>
    <origin xyz="0 ${-(body_width/2 + track_width/2)} ${-body_height/2 + track_height/2}" rpy="0 0 0"/>
  </joint>

</robot>
