use_sim_time: true

slam_toolbox:
  ros__parameters:
    use_sim_time: true
    slam_toolbox:
      solver_plugin: solver_plugins::CeresSolver
      ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
      ceres_preconditioner: SCHUR_JACOBI
      ceres_trust_strategy: LEVENBERG_MARQUARDT
      ceres_dogleg_type: TRADITIONAL_DOGLEG
      ceres_loss_function: None

    # Mapping
    resolution: 0.05
    max_laser_range: 10.0
    minimum_time_interval: 0.5
    transform_publish_period: 0.02
    mode: mapping

    # Optimization
    optimize_every_n_scans: 20
    minimum_travel_distance: 0.1
    minimum_travel_heading: 0.1
    loop_search_maximum_distance: 3.0
    loop_search_maximum_angle: 0.2
    loop_match_minimum_chain_size: 10
    loop_match_maximum_variance_coarse: 3.0
    loop_match_maximum_variance_fine: 0.5

    # Frames
    odom_frame: odom
    map_frame: map
    base_frame: base_footprint
    scan_topic: /scan_corrected
