slam_toolbox:
  ros__parameters:
    use_sim_time: True
    odom_frame: "odom"
    map_frame: "map"
    base_frame: "base_footprint"
    scan_topic: "/scan"
    qos_scan:
      reliability: "best_effort"
      history: "keep_last"
      depth: 5
    mode: "mapping"
    transform_timeout: 1.0
    solver_plugin: "solver_plugins::CeresSolver"