# my_robot_description/config/nav2_params.yaml (FINAL CORRECTED VERSION)

amcl:
  ros__parameters:
    use_sim_time: true
    base_frame_id: "base_footprint"
    global_frame_id: "map"
    odom_frame_id: "odom"
    scan_topic: "/scan_corrected"

map_server:
  ros__parameters:
    use_sim_time: true
    yaml_filename: "maps/my_map.yaml"

planner_server:
  ros__parameters:
    use_sim_time: true
    planner_plugins: ["GridBased"]
    GridBased:
      plugin: "nav2_navfn_planner::NavfnPlanner"
      tolerance: 0.5

controller_server:
  ros__parameters:
    use_sim_time: true
    controller_frequency: 20.0
    controller_plugins: ["FollowPath"]
    FollowPath:
      plugin: "dwb_core::DWBLocalPlanner"
      odom_topic: "/odom"
      # ... (other controller params)

bt_navigator:
  ros__parameters:
    use_sim_time: true
    default_bt_xml_filename: "navigate_w_replanning_and_recovery.xml"

global_costmap:
  ros__parameters:
    use_sim_time: true
    global_frame: "map"
    robot_base_frame: "base_footprint"
    plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
    static_layer:
      plugin: "nav2_costmap_2d::StaticLayer"
    obstacle_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
      observation_sources: "scan"
      scan:
        # --- FIX: Changed to /scan_corrected ---
        topic: "/scan_corrected"
        data_type: "LaserScan"
    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"

local_costmap:
  ros__parameters:
    use_sim_time: true
    global_frame: "odom"
    robot_base_frame: "base_footprint"
    plugins: ["obstacle_layer", "inflation_layer"]
    obstacle_layer:
      plugin: "nav2_costmap_2d::ObstacleLayer"
      observation_sources: "scan"
      scan:
        # --- FIX: Changed to /scan_corrected ---
        topic: "/scan_corrected"
        data_type: "LaserScan"
    inflation_layer:
      plugin: "nav2_costmap_2d::InflationLayer"

behavior_server:
  ros__parameters:
    use_sim_time: true

map_saver_server:
  ros__parameters:
    use_sim_time: true

collision_monitor:
  ros__parameters:
    use_sim_time: true
    observation_sources: ["scan"]
    scan:
      # --- FIX: Changed to /scan_corrected ---
      topic: "/scan_corrected"
      type: "LaserScan"

lifecycle_manager:
  ros__parameters:
    use_sim_time: true
    autostart: true
    node_names:
      - "controller_server"
      - "planner_server"
      - "behavior_server"
      - "bt_navigator"
      - "map_server"
      - "amcl"
      - "collision_monitor"