slam_toolbox:
  ros__parameters:
    # Required Parameters
    odom_frame: odom
    map_frame: map
    # This is the critical fix:
    base_frame: base_footprint   # It MUST be 'base_footprint', not 'my_robot/base_footprint'
    
    # This must match the output of your frame_fixer.py
    scan_topic: /scan_corrected

    # General Parameters
    use_sim_time: True
    resolution: 0.05
    map_update_interval: 1.0

    # Mode and Solver Parameters
    mode: mapping
    solver_plugin: "solver_plugins::CeresSolver"
    
    # Other settings...
    ceres_solver_options:
      use_nonmonotonic_steps: false
      max_num_iterations: 50
      num_threads: 1
    map_file_name: ""
    map_start_at_dock: false
    debug_logging: false
    throttle_scans: 1
    transform_publish_period: 0.05
    map_visualization_rate: 0.5

